#!/usr/bin/env bash

BASE=`echo ${1} | sed 's/::/_/g'`

if [[ -f <%= @settings['base_dir'] %>/$BASE ]]; then
	cat $STATE > <%= @settings['base_dir'] %>/$BASE
else
	echo "That statemachine is not configured on this machine"
fi
